package ir.kamranvahdati.lawoffice;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.print.*;
import android.text.InputType;
import android.util.Base64;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import java.io.*;
import java.util.*;

public class MainActivity extends Activity {
  static final int HOME=0,CASES=1,TASKS=2,REPORTS=3,LETTER=4,LAWYER=5,BACKUP=6,SETTINGS=7;
  static final int PHOTO=70,LOGO=71,EXPORT=72,IMPORT=73;
  final int NAVY=Color.rgb(21,36,70),BLUE=Color.rgb(45,86,210),PAPER=Color.rgb(244,247,252),INK=Color.rgb(24,34,54),MUTED=Color.rgb(103,116,139),RED=Color.rgb(187,48,54),GREEN=Color.rgb(31,132,84);
  OfficeDb db; SharedPreferences prefs; LinearLayout root,page; TextView title,subtitle; int active=HOME;
  Deque<Integer> history=new ArrayDeque<>(); Runnable detailBack; String caseStatus="active",caseCategory="همه",selectedDate,pendingCode; boolean clientsTab;
  int calYear,calMonth; WebView printView;

  @Override public void onCreate(Bundle b){super.onCreate(b);try{start();}catch(Throwable e){try{deleteDatabase(OfficeDb.DATABASE_NAME);start();}catch(Throwable x){errorScreen(x);}}}
  void start(){prefs=getSharedPreferences("office_profile",MODE_PRIVATE);db=new OfficeDb(this);JalaliDate j=JalaliDate.today();calYear=j.year;calMonth=j.month;selectedDate=j.value();shell();dashboard();}
  void shell(){getWindow().setStatusBarColor(NAVY);getWindow().setNavigationBarColor(Color.WHITE);root=col();root.setBackgroundColor(PAPER);LinearLayout h=row();h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(12),dp(10),dp(12),dp(10));h.setBackgroundColor(NAVY);TextView menu=txt("⋮",31,Color.WHITE);menu.setGravity(Gravity.CENTER);menu.setOnClickListener(this::menu);h.addView(menu,lp(dp(48),dp(48)));LinearLayout names=col();title=txt("دفتر وکالت",19,Color.WHITE);title.setTypeface(null,Typeface.BOLD);subtitle=txt("کامران وحدتی · وکیل پایه یک دادگستری",11,Color.rgb(197,207,226));names.addView(title);names.addView(subtitle);h.addView(names,weight());TextView add=txt("+",28,Color.WHITE);add.setGravity(Gravity.CENTER);add.setBackground(round(BLUE,13));add.setOnClickListener(v->addTask(null));h.addView(add,lp(dp(44),dp(44)));root.addView(h);ScrollView s=new ScrollView(this);s.setFillViewport(true);page=col();page.setPadding(dp(14),dp(14),dp(14),dp(28));s.addView(page);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);safeArea(root);}
  void safeArea(View v){v.setPadding(0,dp(5),0,dp(5));v.setOnApplyWindowInsetsListener((x,i)->{x.setPadding(0,i.getSystemWindowInsetTop()+dp(5),0,i.getSystemWindowInsetBottom()+dp(5));return i;});v.requestApplyInsets();}
  void menu(View anchor){PopupMenu p=new PopupMenu(this,anchor);String[] a={"میز کار و تقویم","پرونده‌ها و موکلان","برنامه کاری","گزارش‌گیری","لایحه و سربرگ","اطلاعات وکیل","پشتیبان‌گیری امن","تنظیمات"};for(int i=0;i<a.length;i++)p.getMenu().add(0,i,i,a[i]);p.setOnMenuItemClickListener(m->{go(m.getItemId(),true);return true;});p.show();}
  void go(int n,boolean remember){detailBack=null;if(remember&&n!=active)history.push(active);active=n;if(n==HOME)dashboard();else if(n==CASES)casesHub();else if(n==TASKS)tasks();else if(n==REPORTS)reports();else if(n==LETTER)letter();else if(n==LAWYER)lawyer();else if(n==BACKUP)backup();else settings();}
  @Override public void onBackPressed(){if(detailBack!=null){Runnable r=detailBack;detailBack=null;r.run();}else if(!history.isEmpty())go(history.pop(),false);else new AlertDialog.Builder(this).setTitle("خروج از برنامه").setMessage("آیا از برنامه خارج می‌شوید؟").setNegativeButton("خیر",null).setPositiveButton("بله",(d,w)->finish()).show();}
  void clear(String h,String s){page.removeAllViews();title.setText(h);subtitle.setText(s);}

  void dashboard(){clear("میز کار امروز","تقویم شمسی و اولویت‌های کاری");JalaliDate today=JalaliDate.today();LinearLayout hero=col();hero.setPadding(dp(18),dp(17),dp(18),dp(17));hero.setBackground(round(NAVY,18));TextView hi=txt(greeting()+"، کامران وحدتی",20,Color.WHITE);hi.setTypeface(null,Typeface.BOLD);hero.addView(hi);hero.addView(txt("امروز «"+today.day+" "+JalaliDate.monthName(today.month)+" "+today.year+"»",13,Color.rgb(204,214,234)));margin(hero,0,0,0,14);page.addView(hero);LinearLayout stats=row();stats.addView(stat("پرونده جاری",db.countCases("active"),"⚖",BLUE),new LinearLayout.LayoutParams(0,dp(105),1));stats.addView(stat("کار امروز",db.countToday(today.value()),"✓",GREEN),new LinearLayout.LayoutParams(0,dp(105),1));stats.addView(stat("مختومه",db.countCases("closed"),"✓",MUTED),new LinearLayout.LayoutParams(0,dp(105),1));page.addView(stats);ArrayList<OfficeDb.TaskRecord> urgent=new ArrayList<>();for(OfficeDb.TaskRecord t:db.tasksForDate(today.value()))if(t.done==0&&"فوری".equals(t.priority))urgent.add(t);section("اولویت فوری امروز",urgent.isEmpty()?"مورد فوری ثبت نشده":"تعداد: "+urgent.size());if(urgent.isEmpty())page.addView(empty("برای امروز کار فوری ندارید."));else for(OfficeDb.TaskRecord t:urgent)page.addView(taskCard(t));section("تقویم کاری شمسی","برنامه‌ها و مهلت‌های ماه");page.addView(calendar());section("برنامه "+selectedDate,"روز انتخاب‌شده");TextView add=action("+ ثبت برنامه برای این روز");add.setOnClickListener(v->addTask(selectedDate));page.addView(add);List<OfficeDb.TaskRecord> list=db.tasksForDate(selectedDate);if(list.isEmpty())page.addView(empty("برنامه‌ای برای این روز ثبت نشده است."));else for(OfficeDb.TaskRecord t:list)page.addView(taskCard(t));}
  String greeting(){int h=Calendar.getInstance().get(Calendar.HOUR_OF_DAY);return h<12?"صبح بخیر":h<18?"روز بخیر":"شب بخیر";}
  View calendar(){LinearLayout card=col();card.setPadding(dp(12),dp(12),dp(12),dp(14));card.setBackground(round(Color.WHITE,16));LinearLayout bar=row();TextView next=action("ماه بعد ‹"),prev=action("› ماه قبل"),month=txt(JalaliDate.monthName(calMonth)+" "+calYear,16,INK);month.setGravity(Gravity.CENTER);month.setTypeface(null,Typeface.BOLD);bar.addView(next,weight());bar.addView(month,new LinearLayout.LayoutParams(0,dp(42),1.3f));bar.addView(prev,weight());card.addView(bar);prev.setOnClickListener(v->{calMonth--;if(calMonth<1){calMonth=12;calYear--;}selectedDate=ymd(calYear,calMonth,1);dashboard();});next.setOnClickListener(v->{calMonth++;if(calMonth>12){calMonth=1;calYear++;}selectedDate=ymd(calYear,calMonth,1);dashboard();});String[] wd={"ش","ی","د","س","چ","پ","ج"};LinearLayout week=row();for(String w:wd){TextView x=txt(w,12,"ج".equals(w)?RED:MUTED);x.setGravity(Gravity.CENTER);week.addView(x,new LinearLayout.LayoutParams(0,dp(34),1));}card.addView(week);int first=JalaliDate.firstWeekday(calYear,calMonth),days=JalaliDate.monthLength(calYear,calMonth),day=1;for(int r=0;r<6&&day<=days;r++){LinearLayout line=row();for(int c=0;c<7;c++){if((r==0&&c<first)||day>days)line.addView(new Space(this),new LinearLayout.LayoutParams(0,dp(48),1));else{final int d=day++;String value=ymd(calYear,calMonth,d);int count=db.countToday(value);TextView cell=txt(d+(count>0?" •":""),12,value.equals(selectedDate)?Color.WHITE:(c==6?RED:INK));cell.setGravity(Gravity.CENTER);if(value.equals(selectedDate))cell.setBackground(round(BLUE,12));cell.setOnClickListener(v->{selectedDate=value;dashboard();});line.addView(cell,new LinearLayout.LayoutParams(0,dp(48),1));}}card.addView(line);}return card;}

  void casesHub(){clear("پرونده‌ها و موکلان","مدیریت یکپارچه اشخاص و پرونده‌ها");LinearLayout tabs=row();TextView a=tab("پرونده‌ها",!clientsTab),b=tab("اشخاص و موکلان",clientsTab);a.setOnClickListener(v->{clientsTab=false;casesHub();});b.setOnClickListener(v->{clientsTab=true;casesHub();});tabs.addView(a,weight());tabs.addView(b,weight());page.addView(tabs);if(clientsTab)renderClients();else renderCases();}
  void renderCases(){LinearLayout states=row();TextView a=tab("جاری ("+db.countCases("active")+")","active".equals(caseStatus)),b=tab("مختومه ("+db.countCases("closed")+")","closed".equals(caseStatus));a.setOnClickListener(v->{caseStatus="active";casesHub();});b.setOnClickListener(v->{caseStatus="closed";casesHub();});states.addView(a,weight());states.addView(b,weight());margin(states,0,12,0,8);page.addView(states);String[] cats={"همه","کیفری","حقوقی","انقلاب","خانواده","دیوان عدالت اداری","نظامی","سایر"};Spinner filter=spinner(cats);int at=Arrays.asList(cats).indexOf(caseCategory);filter.setSelection(Math.max(0,at));filter.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int pos,long id){String n=cats[pos];if(!n.equals(caseCategory)){caseCategory=n;casesHub();}}});page.addView(filter);TextView add=action("+ ثبت پرونده جدید");add.setOnClickListener(v->addCase());page.addView(add);List<OfficeDb.CaseRecord> list=db.cases(caseStatus,caseCategory,null);if(list.isEmpty())page.addView(empty("در این دسته پرونده‌ای ثبت نشده است."));for(OfficeDb.CaseRecord c:list)page.addView(caseCard(c));}
  void renderClients(){TextView add=action("+ ثبت موکل جدید");add.setOnClickListener(v->addClient(null));page.addView(add);List<OfficeDb.ClientRecord> list=db.clients();if(list.isEmpty())page.addView(empty("هنوز موکلی ثبت نشده است."));for(OfficeDb.ClientRecord c:list)page.addView(clientCard(c));}
  View caseCard(OfficeDb.CaseRecord c){LinearLayout card=col();card.setPadding(dp(15),dp(14),dp(15),dp(14));card.setBackground(round(Color.WHITE,14));margin(card,0,0,0,9);LinearLayout top=row();TextView h=txt(c.title,15,INK);h.setTypeface(null,Typeface.BOLD);top.addView(h,weight());top.addView(badge(safe(c.category),BLUE));card.addView(top);card.addView(txt("موکل: "+safe(c.clientName)+" | شماره: "+safe(c.caseNumber),11,MUTED));card.addView(txt(safe(c.branch)+" | مرحله: "+safe(c.stage),11,MUTED));card.setOnClickListener(v->caseDetail(c));return card;}
  View clientCard(OfficeDb.ClientRecord c){LinearLayout card=col();card.setPadding(dp(15),dp(14),dp(15),dp(14));card.setBackground(round(Color.WHITE,14));margin(card,0,0,0,9);LinearLayout top=row();TextView h=txt(c.name,15,INK);h.setTypeface(null,Typeface.BOLD);top.addView(h,weight());top.addView(badge(c.activeCount+" جاری از "+c.caseCount,GREEN));card.addView(top);card.addView(txt("تلفن: "+safe(c.phone)+" | کد ملی: "+safe(c.nationalId),11,MUTED));card.addView(txt("نشانی: "+safe(c.address),11,MUTED));card.setOnClickListener(v->clientCases(c));return card;}
  void clientCases(OfficeDb.ClientRecord c){clear("پرونده‌های "+c.name,"تعداد کل: "+c.caseCount);detailBack=()->{clientsTab=true;casesHub();};List<OfficeDb.CaseRecord> list=db.cases(null,"همه",c.id);if(list.isEmpty())page.addView(empty("برای این موکل پرونده‌ای ثبت نشده است."));for(OfficeDb.CaseRecord x:list)page.addView(caseCard(x));}
  void caseDetail(OfficeDb.CaseRecord c){clear(c.title,("active".equals(c.status)?"پرونده جاری":"پرونده مختومه")+" · "+safe(c.category));detailBack=this::casesHub;page.addView(info("اطلاعات پرونده","شماره پرونده: "+safe(c.caseNumber)+"\nشماره بایگانی: "+safe(c.archiveNumber)+"\nمرجع: "+safe(c.reference)+"\nشعبه: "+safe(c.branch)+"\nمرحله: "+safe(c.stage)+"\nموکل: "+safe(c.clientName)));page.addView(info("موضوع و مبانی","موضوع: "+safe(c.subject)+"\nخواسته/شکایت: "+safe(c.claimText)+"\nدلایل: "+safe(c.evidence)+"\nشرح مختصر: "+safe(c.summary)));page.addView(info("وکالت و امور مالی","حق‌الوکاله: "+money(c.feeAgreed)+"\nتوافق: "+safe(c.agreementNotes)+"\nعقد وکالت: "+safe(c.contractNotes)+"\nیادداشت مالی: "+safe(c.financialNotes)));LinearLayout buttons=row();TextView status=action("active".equals(c.status)?"انتقال به مختومه":"بازگشت به جاری"),finance=action("حسابداری پرونده");status.setOnClickListener(v->{db.updateCaseStatus(c.id,"active".equals(c.status)?"closed":"active");caseStatus="active".equals(c.status)?"closed":"active";casesHub();});finance.setOnClickListener(v->finance(c));buttons.addView(status,weight());buttons.addView(finance,weight());page.addView(buttons);}
  void finance(OfficeDb.CaseRecord c){clear("حسابداری پرونده",c.title);detailBack=()->caseDetail(c);OfficeDb.AccountSummary a=db.summary(c);LinearLayout stats=row();stats.addView(stat("دریافت",a.received,"ریال",GREEN),new LinearLayout.LayoutParams(0,dp(108),1));stats.addView(stat("بدهی موکل",a.debt,"ریال",RED),new LinearLayout.LayoutParams(0,dp(108),1));page.addView(stats);page.addView(info("جمع‌بندی مالی","حق‌الوکاله: "+money(a.agreed)+"\nکل هزینه‌ها: "+money(a.expenses)+"\nپرداخت وکیل: "+money(a.lawyerPaid)+"\nبازپرداخت موکل: "+money(a.reimbursed)+"\nبستانکاری موکل: "+money(a.credit)));TextView add=action("+ ثبت دریافت یا هزینه");add.setOnClickListener(v->addLedger(c));page.addView(add);for(OfficeDb.LedgerRecord l:db.ledger(c.id))page.addView(info(l.category+" · "+money(l.amount),safe(l.date)+" | پرداخت‌کننده: "+safe(l.paidBy)+"\n"+safe(l.description)));}

  void tasks(){clear("برنامه کاری","جلسات، مهلت‌ها و کارهای آتی");TextView add=action("+ افزودن کار، جلسه یا مهلت");add.setOnClickListener(v->addTask(null));page.addView(add);List<OfficeDb.TaskRecord> list=db.openTasks(200);if(list.isEmpty())page.addView(empty("کار بازی ثبت نشده است."));for(OfficeDb.TaskRecord t:list)page.addView(taskCard(t));}
  View taskCard(OfficeDb.TaskRecord t){LinearLayout card=row();card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(12),dp(11),dp(12),dp(11));card.setBackground(round(Color.WHITE,13));margin(card,0,0,0,8);CheckBox done=new CheckBox(this);done.setChecked(t.done==1);done.setOnCheckedChangeListener((b,c)->{db.setTaskDone(t.id,c);if(active==HOME)dashboard();else tasks();});card.addView(done);LinearLayout body=col();TextView h=txt(t.title,14,INK);h.setTypeface(null,Typeface.BOLD);body.addView(h);body.addView(txt(safe(t.date)+" · "+safe(t.time)+" · "+safe(t.caseName),10,MUTED));if(!blank(t.notes))body.addView(txt(t.notes,10,MUTED));card.addView(body,weight());card.addView(badge(t.priority,"فوری".equals(t.priority)?RED:BLUE));return card;}

  void addTask(String preset){LinearLayout f=form();EditText name=input("عنوان کار یا جلسه"),related=input("پرونده یا موکل مرتبط"),date=input("تاریخ شمسی"),time=input("ساعت، مثال ۰۹:۳۰"),notes=area("توضیحات و محل جلسه");date.setText(preset==null?JalaliDate.today().value():preset);Spinner priority=spinner(new String[]{"فوری","عادی","کم"});for(View v:new View[]{name,related,date,time,priority,notes})f.addView(v);new AlertDialog.Builder(this).setTitle("ثبت برنامه جدید").setView(scroll(f)).setNegativeButton("انصراف",null).setPositiveButton("ذخیره",(d,w)->{if(blank(name.getText().toString())){toast("عنوان الزامی است");return;}db.addTask(name.getText().toString(),related.getText().toString(),date.getText().toString(),time.getText().toString(),priority.getSelectedItem().toString(),notes.getText().toString());selectedDate=date.getText().toString();if(active==HOME)dashboard();else tasks();}).show();}
  void addClient(Runnable after){LinearLayout f=form();EditText name=input("نام و نام خانوادگی"),national=input("کد ملی"),father=input("نام پدر"),birth=input("تاریخ تولد"),phone=input("تلفن"),address=area("نشانی"),notes=area("توضیحات");for(View v:new View[]{name,national,father,birth,phone,address,notes})f.addView(v);new AlertDialog.Builder(this).setTitle("موکل جدید").setView(scroll(f)).setNegativeButton("انصراف",null).setPositiveButton("ذخیره",(d,w)->{if(blank(name.getText().toString())){toast("نام موکل الزامی است");return;}db.addClient(name.getText().toString(),national.getText().toString(),father.getText().toString(),birth.getText().toString(),phone.getText().toString(),address.getText().toString(),notes.getText().toString());if(after!=null)after.run();else{clientsTab=true;casesHub();}}).show();}
  void addCase(){List<OfficeDb.ClientRecord> clients=db.clients();ArrayList<String> names=new ArrayList<>();names.add("بدون موکل");for(OfficeDb.ClientRecord c:clients)names.add(c.name);LinearLayout f=form();EditText title=input("عنوان پرونده *"),number=input("شماره پرونده"),archive=input("شماره بایگانی"),reference=input("مرجع قضایی"),branch=input("شعبه"),stage=input("مرحله رسیدگی"),subject=input("موضوع پرونده"),claim=area("خواسته، شکایت یا اتهام"),evidence=area("دلایل و مستندات"),summary=area("شرح مختصر پرونده"),fee=input("حق‌الوکاله به ریال"),agreement=area("توافقات مالی"),contract=area("عقد وکالت و شرایط"),financial=area("یادداشت مالی");fee.setInputType(InputType.TYPE_CLASS_NUMBER);Spinner category=spinner(new String[]{"کیفری","حقوقی","انقلاب","خانواده","دیوان عدالت اداری","نظامی","سایر"}),status=spinner(new String[]{"جاری","مختومه"}),client=spinner(names.toArray(new String[0]));TextView nc=action("+ افزودن موکل جدید از همین قسمت");nc.setOnClickListener(v->addClient(this::addCase));for(View v:new View[]{title,number,archive,reference,branch,category,status,client,nc,stage,subject,claim,evidence,summary,fee,agreement,contract,financial})f.addView(v);new AlertDialog.Builder(this).setTitle("ثبت کامل پرونده").setView(scroll(f)).setNegativeButton("انصراف",null).setPositiveButton("ذخیره",(d,w)->{if(blank(title.getText().toString())){toast("عنوان پرونده الزامی است");return;}OfficeDb.CaseRecord c=new OfficeDb.CaseRecord();c.title=title.getText().toString();c.caseNumber=number.getText().toString();c.archiveNumber=archive.getText().toString();c.reference=reference.getText().toString();c.branch=branch.getText().toString();c.category=category.getSelectedItem().toString();c.status=status.getSelectedItemPosition()==0?"active":"closed";if(client.getSelectedItemPosition()>0)c.clientId=clients.get(client.getSelectedItemPosition()-1).id;c.stage=stage.getText().toString();c.subject=subject.getText().toString();c.claimText=claim.getText().toString();c.evidence=evidence.getText().toString();c.summary=summary.getText().toString();c.feeAgreed=parseMoney(fee.getText().toString());c.agreementNotes=agreement.getText().toString();c.contractNotes=contract.getText().toString();c.financialNotes=financial.getText().toString();db.addCase(c);caseStatus=c.status;clientsTab=false;casesHub();}).show();}
  void addLedger(OfficeDb.CaseRecord c){LinearLayout f=form();Spinner kind=spinner(new String[]{"دریافت حق‌الوکاله","بازپرداخت هزینه توسط موکل","هزینه پرونده"}),category=spinner(new String[]{"حق‌الوکاله","بازپرداخت هزینه","هزینه دادرسی","کارشناسی","تمبر و خدمات قضایی","هتل","بلیط هواپیما","تاکسی و فرودگاه","اقامت و مأموریت","سایر"}),paid=spinner(new String[]{"موکل","وکیل","شخص ثالث"});EditText amount=input("مبلغ به ریال"),date=input("تاریخ شمسی"),desc=area("شرح هزینه یا پرداخت");amount.setInputType(InputType.TYPE_CLASS_NUMBER);date.setText(JalaliDate.today().value());for(View v:new View[]{kind,category,amount,date,paid,desc})f.addView(v);new AlertDialog.Builder(this).setTitle("ثبت عملیات مالی").setView(scroll(f)).setNegativeButton("انصراف",null).setPositiveButton("ذخیره",(d,w)->{String k=kind.getSelectedItemPosition()==2?"expense":"payment",cat=kind.getSelectedItemPosition()==0?"حق‌الوکاله":kind.getSelectedItemPosition()==1?"بازپرداخت هزینه":category.getSelectedItem().toString();db.addLedger(c.id,k,cat,parseMoney(amount.getText().toString()),date.getText().toString(),paid.getSelectedItem().toString(),desc.getText().toString());finance(c);}).show();}

  void reports(){clear("گزارش‌گیری","خروجی فهرست‌ها، پرونده‌ها و امور مالی");String[][] a={{"گزارش موکلان","نام، تلفن، نشانی و تعداد پرونده"},{"پرونده‌های جاری","همه پرونده‌های در حال پیگیری"},{"پرونده‌های مختومه","فهرست سوابق مختومه"},{"گزارش کیفری","پرونده‌های کیفری"},{"گزارش حقوقی","پرونده‌های حقوقی"},{"گزارش خانواده","پرونده‌های خانواده"},{"گزارش جامع مالی","حق‌الوکاله، هزینه، بدهی و طلب"}};for(int i=0;i<a.length;i++){final int n=i;View v=info(a[i][0],a[i][1]+"\nبرای پیش‌نمایش و PDF لمس کنید.");v.setOnClickListener(x->runReport(n));page.addView(v);}}
  void runReport(int type){String heading,body;if(type==0){heading="گزارش موکلان";StringBuilder b=new StringBuilder();for(OfficeDb.ClientRecord c:db.clients())b.append(c.name).append("\nتلفن: ").append(safe(c.phone)).append(" | کد ملی: ").append(safe(c.nationalId)).append("\nنشانی: ").append(safe(c.address)).append("\nپرونده‌ها: ").append(c.caseCount).append(" (جاری: ").append(c.activeCount).append(")\n\n");body=b.toString();}else if(type==6){heading="گزارش جامع مالی";StringBuilder b=new StringBuilder();for(OfficeDb.CaseRecord c:db.cases(null,"همه",null)){OfficeDb.AccountSummary a=db.summary(c);b.append(c.title).append(" | موکل: ").append(safe(c.clientName)).append("\nحق‌الوکاله: ").append(money(a.agreed)).append(" | دریافتی: ").append(money(a.received)).append("\nهزینه: ").append(money(a.expenses)).append(" | بدهی: ").append(money(a.debt)).append(" | بستانکاری: ").append(money(a.credit)).append("\nتوافق: ").append(safe(c.agreementNotes)).append("\n\n");}body=b.toString();}else{String status=type==1?"active":type==2?"closed":null,cat=type==3?"کیفری":type==4?"حقوقی":type==5?"خانواده":"همه";heading=type==1?"پرونده‌های جاری":type==2?"پرونده‌های مختومه":"پرونده‌های "+cat;StringBuilder b=new StringBuilder();for(OfficeDb.CaseRecord c:db.cases(status,cat,null))b.append(c.title).append("\nشماره: ").append(safe(c.caseNumber)).append(" | بایگانی: ").append(safe(c.archiveNumber)).append("\nموکل: ").append(safe(c.clientName)).append(" | دسته: ").append(safe(c.category)).append("\nموضوع: ").append(safe(c.subject)).append(" | شعبه: ").append(safe(c.branch)).append("\n\n");body=b.toString();}preview(heading,body);}
  void preview(String h,String body){ScrollView s=new ScrollView(this);TextView v=txt(body,13,INK);v.setPadding(dp(18),dp(14),dp(18),dp(14));v.setTextIsSelectable(true);s.addView(v);new AlertDialog.Builder(this).setTitle(h).setView(s).setNegativeButton("بستن",null).setPositiveButton("PDF / چاپ",(d,w)->print(h,html(h,body))).show();}

  void letter(){clear("لایحه و سربرگ","تنظیم متن و دریافت PDF رسمی");List<OfficeDb.CaseRecord> cases=db.cases(null,"همه",null);ArrayList<String> names=new ArrayList<>();names.add("بدون اتصال به پرونده");for(OfficeDb.CaseRecord c:cases)names.add(c.title);Spinner pick=spinner(names.toArray(new String[0]));EditText subject=input("عنوان لایحه یا نامه"),body=area("متن کامل لایحه را اینجا وارد کنید...");body.setMinLines(12);TextView p=action("ساخت سربرگ و خروجی PDF");p.setOnClickListener(v->{OfficeDb.CaseRecord c=pick.getSelectedItemPosition()>0?cases.get(pick.getSelectedItemPosition()-1):null;String meta=c==null?"":"شماره پرونده: "+safe(c.caseNumber)+" | بایگانی: "+safe(c.archiveNumber)+" | شعبه: "+safe(c.branch)+"\n";print(subject.getText().toString(),html(subject.getText().toString(),meta+body.getText().toString()));});page.addView(pick);page.addView(subject);page.addView(body);page.addView(p);page.addView(info("راهنما","مشخصات وکیل و لوگو از بخش اطلاعات وکیل روی سربرگ درج می‌شود. در صفحه چاپ، Save as PDF را انتخاب کنید."));}
  void lawyer(){clear("اطلاعات وکیل","مشخصات سربرگ و گزارش‌ها");LinearLayout images=row();ImageView photo=image(prefs.getString("photo",null)),logo=image(prefs.getString("logo",null));images.addView(photo,new LinearLayout.LayoutParams(0,dp(125),1));images.addView(logo,new LinearLayout.LayoutParams(0,dp(125),1));page.addView(images);LinearLayout choose=row();TextView p=action("انتخاب عکس وکیل"),l=action("انتخاب لوگوی کانون/مرکز");p.setOnClickListener(v->pickImage(PHOTO));l.setOnClickListener(v->pickImage(LOGO));choose.addView(p,weight());choose.addView(l,weight());page.addView(choose);EditText name=input("نام و نام خانوادگی"),license=input("شماره پروانه وکالت"),center=input("کانون یا مرکز وکلا"),phone=input("شماره تلفن"),address=area("نشانی دفتر"),website=input("وب‌سایت");name.setText(prefs.getString("name","کامران وحدتی"));license.setText(prefs.getString("license",""));center.setText(prefs.getString("center","کانون وکلای دادگستری مرکز"));phone.setText(prefs.getString("phone",""));address.setText(prefs.getString("address",""));website.setText(prefs.getString("website","kamranvahdati.ir"));for(View v:new View[]{name,license,center,phone,address,website})page.addView(v);TextView save=action("ذخیره اطلاعات وکیل");save.setOnClickListener(v->{prefs.edit().putString("name",name.getText().toString()).putString("license",license.getText().toString()).putString("center",center.getText().toString()).putString("phone",phone.getText().toString()).putString("address",address.getText().toString()).putString("website",website.getText().toString()).apply();toast("اطلاعات وکیل ذخیره شد");});page.addView(save);}
  void pickImage(int code){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,code);}

  void backup(){clear("پشتیبان‌گیری امن","انتقال کنترل‌شده اطلاعات بین گوشی‌ها");page.addView(info("روش امن آفلاین","یک فایل رمزگذاری‌شده با پسوند .klo ساخته می‌شود. شما مقصد یا دریافت‌کننده را انتخاب می‌کنید و گوشی مقصد فقط با همان کد قادر به بازیابی است. کد را جداگانه منتقل کنید."));EditText code=input("کد پشتیبان حداقل ۶ رقم یا حرف");code.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);TextView export=action("ساخت فایل پشتیبان رمزگذاری‌شده"),restore=action("بازیابی فایل پشتیبان در این گوشی");export.setOnClickListener(v->{if(code.length()<6){toast("کد حداقل ۶ کاراکتر باشد");return;}pendingCode=code.getText().toString();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/octet-stream");i.putExtra(Intent.EXTRA_TITLE,"دفتر-وکالت-"+JalaliDate.today().value().replace('/','-')+".klo");startActivityForResult(i,EXPORT);});restore.setOnClickListener(v->{if(code.length()<6){toast("ابتدا کد فایل را وارد کنید");return;}pendingCode=code.getText().toString();new AlertDialog.Builder(this).setTitle("تأیید بازیابی").setMessage("اطلاعات فعلی با محتوای فایل جایگزین می‌شود. ادامه می‌دهید؟").setNegativeButton("خیر",null).setPositiveButton("ادامه",(d,w)->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMPORT);}).show();});page.addView(code);page.addView(export);page.addView(restore);}
  @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();try{if(req==PHOTO||req==LOGO){getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);prefs.edit().putString(req==PHOTO?"photo":"logo",uri.toString()).apply();lawyer();}else if(req==EXPORT){byte[] bytes=SecureBackup.encrypt(db.exportJson(),pendingCode);try(OutputStream out=getContentResolver().openOutputStream(uri)){out.write(bytes);}toast("پشتیبان رمزگذاری‌شده ذخیره شد");}else if(req==IMPORT){db.importJson(SecureBackup.decrypt(readAll(uri),pendingCode));toast("اطلاعات بازیابی شد");go(HOME,false);}}catch(Exception e){new AlertDialog.Builder(this).setTitle("عملیات انجام نشد").setMessage("کد نادرست است یا فایل معتبر نیست.\n\n"+e.getClass().getSimpleName()).setPositiveButton("باشه",null).show();}finally{pendingCode=null;}}
  byte[] readAll(Uri uri)throws Exception{try(InputStream in=getContentResolver().openInputStream(uri);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return out.toByteArray();}}
  void settings(){clear("تنظیمات","نسخه آزمایشی عمومی");page.addView(info("نسخه برنامه","نسخه ۰٫۵٫۰ — پایگاه داده محلی"));page.addView(info("حریم خصوصی","برنامه برای کارکرد اصلی به اینترنت دسترسی ندارد و اطلاعات روی همین گوشی ذخیره می‌شود."));page.addView(info("دسته‌بندی‌ها","کیفری، حقوقی، انقلاب، خانواده، دیوان عدالت اداری، نظامی و سایر."));}

  String html(String heading,String body){String logo=imageData(prefs.getString("logo",null)),img=blank(logo)?"":"<img src='"+logo+"' style='width:72px;height:72px;object-fit:contain'>",name=esc(prefs.getString("name","کامران وحدتی")),license=esc(prefs.getString("license","")),center=esc(prefs.getString("center","")),phone=esc(prefs.getString("phone","")),address=esc(prefs.getString("address","")),web=esc(prefs.getString("website",""));return "<!doctype html><html dir='rtl'><head><meta charset='utf-8'><style>@page{size:A4;margin:18mm}body{font-family:sans-serif;direction:rtl;color:#182236;line-height:2}.head{display:flex;align-items:center;border-bottom:3px solid #152446;padding-bottom:12px}.brand{flex:1}h1,h2,p{margin:0}.meta{font-size:12px;color:#566176}.body{white-space:pre-wrap;margin-top:28px;font-size:14px}.foot{margin-top:50px;border-top:1px solid #bbb;padding-top:8px;font-size:11px}</style></head><body><div class='head'>"+img+"<div class='brand'><h1>دفتر وکالت "+name+"</h1><p>وکیل پایه یک دادگستری · "+center+"</p><p class='meta'>شماره پروانه: "+license+"</p></div></div><h2 style='text-align:center;margin-top:24px'>"+esc(heading)+"</h2><div class='body'>"+esc(body)+"</div><div class='foot'>تلفن: "+phone+" | نشانی: "+address+" | "+web+"</div></body></html>";}
  void print(String name,String html){printView=new WebView(this);printView.getSettings().setDefaultTextEncodingName("UTF-8");printView.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){PrintManager pm=(PrintManager)getSystemService(PRINT_SERVICE);pm.print(name,v.createPrintDocumentAdapter(name),new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).build());}});printView.loadDataWithBaseURL(null,html,"text/html","UTF-8",null);}
  String imageData(String value){if(blank(value))return "";try(InputStream in=getContentResolver().openInputStream(Uri.parse(value));ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return "data:image/jpeg;base64,"+Base64.encodeToString(out.toByteArray(),Base64.NO_WRAP);}catch(Exception e){return "";}}

  View stat(String label,long value,String icon,int color){LinearLayout b=col();b.setGravity(Gravity.CENTER);b.setPadding(dp(3),dp(7),dp(3),dp(7));b.setBackground(round(Color.WHITE,14));margin(b,3,0,3,0);b.addView(txt(icon,18,color));TextView n=txt(String.format(Locale.US,"%,d",value),16,INK);n.setGravity(Gravity.CENTER);n.setTypeface(null,Typeface.BOLD);b.addView(n);TextView l=txt(label,10,MUTED);l.setGravity(Gravity.CENTER);b.addView(l);return b;}
  void section(String h,String sub){TextView a=txt(h,16,INK);a.setTypeface(null,Typeface.BOLD);a.setPadding(dp(2),dp(20),dp(2),0);page.addView(a);TextView b=txt(sub,10,MUTED);b.setPadding(dp(2),0,dp(2),dp(9));page.addView(b);}
  View info(String h,String body){LinearLayout c=col();c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(round(Color.WHITE,14));margin(c,0,0,0,10);TextView x=txt(h,15,INK);x.setTypeface(null,Typeface.BOLD);c.addView(x);TextView y=txt(body,12,MUTED);y.setPadding(0,dp(7),0,0);y.setLineSpacing(3,1.18f);c.addView(y);return c;}
  TextView tab(String s,boolean on){TextView t=txt(s,13,on?Color.WHITE:BLUE);t.setGravity(Gravity.CENTER);t.setPadding(dp(7),dp(11),dp(7),dp(11));t.setBackground(round(on?BLUE:Color.WHITE,12));margin(t,3,0,3,0);return t;}
  TextView badge(String s,int color){TextView t=txt(s,10,color);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(4),dp(8),dp(4));t.setBackground(round(Color.rgb(238,242,250),20));return t;}
  TextView action(String s){TextView t=txt(s,13,BLUE);t.setGravity(Gravity.CENTER);t.setPadding(dp(10),dp(13),dp(10),dp(13));t.setBackground(round(Color.WHITE,12));margin(t,3,5,3,5);return t;}
  TextView empty(String s){TextView t=txt(s,13,MUTED);t.setGravity(Gravity.CENTER);t.setPadding(dp(10),dp(28),dp(10),dp(28));return t;}
  LinearLayout form(){LinearLayout f=col();f.setPadding(dp(20),dp(8),dp(20),dp(8));return f;} ScrollView scroll(View v){ScrollView s=new ScrollView(this);s.addView(v);return s;}
  EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(14);e.setSingleLine(true);e.setPadding(dp(10),dp(7),dp(10),dp(7));e.setLayoutParams(lp(-1,dp(55)));return e;} EditText area(String h){EditText e=input(h);e.setSingleLine(false);e.setGravity(Gravity.TOP|Gravity.RIGHT);e.setMinLines(3);e.setLayoutParams(lp(-1,-2));return e;}
  Spinner spinner(String[] a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a));s.setLayoutParams(lp(-1,dp(54)));return s;} ImageView image(String uri){ImageView i=new ImageView(this);i.setScaleType(ImageView.ScaleType.CENTER_CROP);i.setPadding(dp(4),dp(4),dp(4),dp(4));i.setBackground(round(Color.WHITE,14));if(!blank(uri))try{i.setImageURI(Uri.parse(uri));}catch(Exception ignored){}return i;}
  LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return l;} LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return l;} TextView txt(String s,int z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setTextDirection(View.TEXT_DIRECTION_RTL);return t;}
  GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w,h);} LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,-2,1);} void margin(View v,int l,int t,int r,int b){LinearLayout.LayoutParams p=v.getLayoutParams() instanceof LinearLayout.LayoutParams?(LinearLayout.LayoutParams)v.getLayoutParams():new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));v.setLayoutParams(p);} int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
  boolean blank(String s){return s==null||s.trim().isEmpty();} String safe(String s){return blank(s)?"ثبت نشده":s;} long parseMoney(String s){try{return Long.parseLong(s.replace(",","").replace("٬","").trim());}catch(Exception e){return 0;}} String money(long v){return String.format(Locale.US,"%,d ریال",v);} String ymd(int y,int m,int d){return String.format(Locale.US,"%04d/%02d/%02d",y,m,d);} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();} String esc(String s){if(s==null)return "";return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\n","<br>");}
  void errorScreen(Throwable e){LinearLayout f=col();f.setGravity(Gravity.CENTER);f.setPadding(dp(24),dp(24),dp(24),dp(24));f.addView(txt("برنامه با خطا روبه‌رو شد\n\n"+e.getClass().getSimpleName()+": "+safe(e.getMessage()),15,RED));setContentView(f);safeArea(f);}
}
