package ir.kamranvahdati.lawoffice;

import android.app.AlertDialog;
import android.content.ContentValues;
import android.view.View;
import android.widget.*;
import java.util.*;

/** Forms for the scoped 10.1 additions; existing screen, theme and accounting helpers are reused. */
final class OfficeV101Ui {
    final MainActivity a;
    final OfficeV101 data;
    OfficeV101Ui(MainActivity activity){a=activity;data=new OfficeV101(a.db);}
    interface Save { void run() throws Exception; }
    void dialog(String title,LinearLayout form,Save save,Runnable after){
        AlertDialog d=new AlertDialog.Builder(a).setTitle(title).setView(a.scroll(form)).setNegativeButton("انصراف",null).setPositiveButton("ذخیره",null).create();
        d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{try{save.run();d.dismiss();if(after!=null)after.run();}catch(Exception e){a.toast(e.getMessage()==null?"اطلاعات معتبر نیست":e.getMessage());}}));d.show();
    }
    TextView button(String label,Runnable action){TextView b=a.action(label);b.setOnClickListener(v->action.run());return b;}
    EditText field(LinearLayout form,String label,String value){EditText e=a.input(label);e.setText(value);form.addView(e);return e;}
    String value(EditText e){return e.getText().toString().trim();}
    void people(){
        a.clear("اشخاص حقیقی و حقوقی","اطلاعات مشترک اشخاص در پرونده و قرارداد");
        a.page.addView(button("+ ثبت شخص",()->addPerson(this::people)));a.page.addView(button("وکلای همکار",this::colleagues));
        EditText search=a.input("جست‌وجوی نام، کد/شناسه ملی یا همراه");a.page.addView(search);
        LinearLayout results=a.col();a.page.addView(results);
        Runnable render=()->{results.removeAllViews();String q=InputValidators.normalizeDigits(value(search));for(ContentValues p:data.persons()){
            if(!(OfficeV101.text(p,"name")+" "+OfficeV101.text(p,"national_id")+" "+OfficeV101.text(p,"phone")).contains(q))continue;
            View card=a.info(OfficeV101.text(p,"name"),("legal".equals(OfficeV101.text(p,"person_type"))?"شخص حقوقی":"شخص حقیقی")+"\n"+OfficeV101.text(p,"phone")+" | "+OfficeV101.text(p,"national_id"));
            card.setOnClickListener(v->personDetails(p.getAsLong("id")));results.addView(card);
        }if(results.getChildCount()==0)results.addView(a.empty("شخصی مطابق جست‌وجو ثبت نشده است."));};
        search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int af){}public void onTextChanged(CharSequence s,int st,int before,int count){render.run();}public void afterTextChanged(android.text.Editable e){}});render.run();
    }
    void person(Long id,Runnable after){person(id,after,-1);}
    void person(Long id,Runnable after,int preset){
        ContentValues old=id==null?new ContentValues():data.person(id);LinearLayout f=a.form();
        Spinner type=a.spinner(new String[]{"شخص حقیقی","شخص حقوقی"});type.setSelection(preset>=0?preset:"legal".equals(OfficeV101.text(old,"person_type"))?1:0);f.addView(type);
        LinkedHashMap<String,EditText> fields=new LinkedHashMap<>();String[][] spec={{"name","نام کامل / نام شخص حقوقی *"},{"first_name","نام"},{"last_name","نام خانوادگی"},{"national_id","کد ملی / شناسه ملی"},{"father_name","نام پدر"},{"birth_date","تاریخ تولد شمسی"},{"legal_type","نوع شخص حقوقی"},{"registration_number","شماره ثبت"},{"registration_date","تاریخ ثبت شمسی"},{"representative","نماینده شخص حقوقی"},{"phone","شماره همراه"},{"telephone","تلفن ثابت"},{"province","استان"},{"city","شهر"},{"postal_code","کد پستی"},{"address","نشانی"},{"notes","توضیحات"}};
        for(String[] item:spec)fields.put(item[0],field(f,item[1],OfficeV101.text(old,item[0])));
        EditText legalType=fields.get("legal_type");legalType.setFocusable(false);legalType.setOnClickListener(v->{String[] choices={"شرکت","مؤسسه","نهاد عمومی","دستگاه دولتی","نهاد غیردولتی","سایر"};new AlertDialog.Builder(a).setTitle("نوع شخص حقوقی").setItems(choices,(d,n)->legalType.setText(choices[n])).show();});
        a.bindJalaliPicker(fields.get("birth_date"));a.bindJalaliPicker(fields.get("registration_date"));a.bindLocation(fields.get("province"),fields.get("city"));
        Runnable visibility=()->{boolean legal=type.getSelectedItemPosition()==1;for(String k:new String[]{"first_name","last_name","father_name","birth_date"})fields.get(k).setVisibility(legal?View.GONE:View.VISIBLE);for(String k:new String[]{"legal_type","registration_number","registration_date","representative"})fields.get(k).setVisibility(legal?View.VISIBLE:View.GONE);};
        type.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int pos,long row){visibility.run();}});visibility.run();
        dialog(id==null?"ثبت شخص":"ویرایش شخص",f,()->{ContentValues values=new ContentValues();for(Map.Entry<String,EditText> e:fields.entrySet())values.put(e.getKey(),value(e.getValue()));values.put("person_type",type.getSelectedItemPosition()==1?"legal":"natural");if(id==null&&type.getSelectedItemPosition()==0){OfficeV101.required(value(fields.get("first_name")),"نام");OfficeV101.required(value(fields.get("last_name")),"نام خانوادگی");if(value(fields.get("name")).isEmpty())values.put("name",value(fields.get("first_name"))+" "+value(fields.get("last_name")));}data.savePerson(id,values);},after);
    }
    void roles(OfficeDb.CaseRecord c){
        a.clear("اشخاص و نقش‌ها",c.title);a.detailBack=()->a.caseDetail(c);
        a.page.addView(button("+ ثبت نقش شخص موجود",()->{LinearLayout f=a.form();Choice people=new Choice(f,"انتخاب شخص",data.persons(),"name");Spinner role=a.spinner(OfficeV101.ROLES);f.addView(role);dialog("اتصال شخص به پرونده",f,()->{if(people.id()==null)throw new IllegalArgumentException("شخص را انتخاب کنید");data.role(c.id,people.id(),role.getSelectedItem().toString());},()->roles(c));}));
        a.page.addView(button("+ ثبت شخص",()->person(null,()->roles(c))));
        for(ContentValues p:data.roles(c.id))a.page.addView(a.info(OfficeV101.text(p,"name"),OfficeV101.text(p,"role")));
    }
    final class Choice {
        final Spinner spinner;final List<ContentValues> rows;
        Choice(LinearLayout form,String prompt,List<ContentValues> list,String label){rows=list;ArrayList<String> labels=new ArrayList<>();labels.add(prompt+" — انتخاب نشده");for(ContentValues r:list)labels.add(OfficeV101.text(r,label)+" · "+r.getAsLong("id"));spinner=a.spinner(labels.toArray(new String[0]));form.addView(spinner);}
        Long id(){int pos=spinner.getSelectedItemPosition();return pos==0?null:rows.get(pos-1).getAsLong("id");}
    }
    List<ContentValues> cases(){return data.rows("SELECT id,title FROM cases WHERE deleted_at IS NULL ORDER BY title");}
    List<ContentValues> accounts(){return data.rows("SELECT * FROM financial_accounts WHERE deleted_at IS NULL ORDER BY name");}
    void accounting(){
        a.clear("حسابداری","دریافتی، پرداختی و هزینه‌ها — ریال");
        a.page.addView(button("+ ثبت دریافتی",()->transaction(false,this::accounting)));a.page.addView(button("+ ثبت پرداختی / هزینه",()->transaction(true,this::accounting)));
        a.page.addView(button("حساب‌ها و بانک‌ها",this::accountList));a.page.addView(button("چک‌ها و حسابداری پرونده",this::checks));
        LinearLayout filters=a.form();Choice person=new Choice(filters,"شخص",data.persons(),"name"),casePick=new Choice(filters,"پرونده",cases(),"title"),account=new Choice(filters,"حساب / بانک",accounts(),"name");
        Spinner kind=a.spinner(new String[]{"همه تراکنش‌ها","دریافتی","پرداختی / هزینه"});filters.addView(kind);EditText start=field(filters,"از تاریخ شمسی",""),end=field(filters,"تا تاریخ شمسی","");a.bindJalaliPicker(start);a.bindJalaliPicker(end);a.page.addView(filters);
        a.page.addView(button("نمایش گزارش",()->{try{String from=value(start),to=value(end);if(!from.isEmpty()&&!to.isEmpty()&&OfficeV101.date(from).compareTo(OfficeV101.date(to))>0)throw new IllegalArgumentException("بازه تاریخ نامعتبر است");List<ContentValues> rows=data.transactions(casePick.id(),person.id(),account.id(),kind.getSelectedItemPosition()==0?null:kind.getSelectedItemPosition()==1?"payment":"expense",from,to);long in=0,out=0;StringBuilder b=new StringBuilder();for(ContentValues row:rows){long amount=row.getAsLong("amount");boolean receipt="payment".equals(OfficeV101.text(row,"kind"));if(receipt)in=Math.addExact(in,amount);else out=Math.addExact(out,amount);b.append(OfficeV101.text(row,"entry_date")).append(" | ").append(receipt?"دریافتی":"پرداختی").append(" | ").append(a.money(amount)).append(" | ").append(OfficeV101.text(row,"category")).append("\n").append(OfficeV101.text(row,"description")).append("\n");}a.preview("گزارش حسابداری","جمع دریافتی: "+a.money(in)+"\nجمع پرداختی: "+a.money(out)+"\nخالص گردش: "+a.money(in-out)+"\n\n"+b);}catch(Exception e){a.toast(e.getMessage());}}));
    }
    void transaction(boolean expense,Runnable after){
        LinearLayout f=a.form();Choice person=new Choice(f,"شخص",data.persons(),"name"),casePick=new Choice(f,"پرونده",cases(),"title"),account=new Choice(f,"حساب / بانک",accounts(),"name"),contract=new Choice(f,"قرارداد الکترونیک وکالت",data.rows("SELECT id,contract_number FROM representation_contracts WHERE deleted_at IS NULL ORDER BY id DESC"),"contract_number"),colleague=new Choice(f,"وکیل همکار",data.rows("SELECT id,first_name||' '||last_name AS name FROM collaborators WHERE deleted_at IS NULL ORDER BY last_name"),"name");
        Spinner category=a.spinner(expense?OfficeV101.EXPENSES:new String[]{"حق‌الوکاله","هزینه","مشاوره","بازپرداخت هزینه","سایر"}),method=a.spinner(new String[]{"نقدی","کارت","حواله بانکی","سایر"}),scope=a.spinner(new String[]{"دفتر","شخصی"});f.addView(category);f.addView(method);f.addView(scope);
        EditText amount=field(f,"مبلغ به ریال *",""),date=field(f,"تاریخ شمسی *",JalaliDate.today().value()),payer=field(f,"پرداخت‌کننده / دریافت‌کننده",""),notes=field(f,"توضیحات","");a.bindJalaliPicker(date);
        dialog(expense?"ثبت پرداختی / هزینه":"ثبت دریافتی",f,()->{ContentValues v=new ContentValues();v.put("kind",expense?"expense":"payment");v.put("category",category.getSelectedItem().toString());v.put("amount",a.positiveMoney(value(amount)));v.put("entry_date",value(date));v.put("paid_by",value(payer));v.put("description",value(notes));v.put("person_id",person.id());v.put("account_id",account.id());v.put("contract_id",contract.id());v.put("collaborator_id",colleague.id());v.put("payment_method",method.getSelectedItem().toString());v.put("scope",scope.getSelectedItemPosition()==0?"office":"personal");data.transaction(casePick.id(),v);},after);
    }
    void accountList(){a.clear("حساب‌ها و بانک‌ها","حساب‌های مورد استفاده در تراکنش‌ها");a.detailBack=this::accounting;a.page.addView(button("+ ثبت حساب",()->{LinearLayout f=a.form();EditText name=field(f,"نام حساب *",""),bank=field(f,"نام بانک",""),number=field(f,"شماره حساب",""),card=field(f,"شماره کارت","");Spinner kind=a.spinner(new String[]{"بانکی","صندوق","سایر"});f.addView(kind);dialog("ثبت حساب",f,()->{ContentValues v=new ContentValues();v.put("name",value(name));v.put("kind",kind.getSelectedItem().toString());v.put("bank",value(bank));v.put("account_number",value(number));v.put("card_number",value(card));data.account(v);},this::accountList);}));for(ContentValues v:accounts())a.page.addView(a.info(OfficeV101.text(v,"name"),OfficeV101.text(v,"bank")+" | "+OfficeV101.text(v,"account_number")));}
    void checks(){a.clear("چک‌ها و حسابداری پرونده","ثبت و تغییر وضعیت با همان گردش مالی موجود");a.detailBack=this::accounting;for(OfficeDb.CaseRecord c:a.db.cases(null,"همه",null))a.page.addView(button(c.title,()->a.finance(c)));if(cases().isEmpty())a.page.addView(a.empty("ابتدا پرونده مرتبط با چک را ثبت کنید."));Spinner state=a.spinner(new String[]{"همه وضعیت‌ها","در انتظار وصول","وصول‌شده","برگشتی","لغوشده"});a.page.addView(state);LinearLayout rows=a.col();a.page.addView(rows);Runnable render=()->{rows.removeAllViews();String[] states={"","pending","collected","bounced","cancelled"};String filter=states[state.getSelectedItemPosition()];for(OfficeDb.PaymentCheckRecord c:a.db.paymentChecks(null,null))if(filter.isEmpty()||filter.equals(c.status))rows.addView(a.info("چک "+c.number,a.money(c.amount)+" | "+c.dueDate+" | "+a.checkStatusLabel(c.status)));};state.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int pos,long id){render.run();}});render.run();}

    void cooperation(){
        a.clear("همکاری وکلا","ثبت محلی؛ اطلاعات برای دیگران ارسال نمی‌شود");
        a.page.addView(button("+ اعلام آمادگی همکاری",()->collaboration("offer")));a.page.addView(button("+ درخواست همکاری",()->collaboration("request")));
        for(ContentValues v:data.rows("SELECT * FROM collaboration_requests WHERE deleted_at IS NULL ORDER BY id DESC"))a.page.addView(a.info(OfficeV101.text(v,"title"),("offer".equals(OfficeV101.text(v,"kind"))?"اعلام آمادگی":"درخواست همکاری")+" | "+OfficeV101.text(v,"province")+"، "+OfficeV101.text(v,"city")+"\n"+OfficeV101.text(v,"description")+"\nثبت‌شده فقط روی این دستگاه"));
    }
    void collaboration(String kind){LinearLayout f=a.form();EditText title=field(f,"عنوان *",""),name=field(f,"نام درخواست‌کننده",a.prefs.getString("name","")),province=field(f,"استان محل همکاری *",""),city=field(f,"شهر محل همکاری *",""),description=field(f,"شرح همکاری",""),specialties=field(f,"تخصص‌ها",""),requesterProvince=field(f,"استان درخواست‌کننده",a.prefs.getString("province","")),requesterCity=field(f,"شهر درخواست‌کننده",a.prefs.getString("city","")),conditions=field(f,"شرایط",""),availability=field(f,"زمان آمادگی",""),due=field(f,"مهلت شمسی",""),amount=field(f,"مبلغ پیشنهادی به ریال","");a.bindLocation(province,city);a.bindLocation(requesterProvince,requesterCity);a.bindJalaliPicker(due);Spinner work=a.spinner(OfficeV101.WORK);f.addView(work);dialog("offer".equals(kind)?"اعلام آمادگی همکاری":"درخواست همکاری",f,()->{ContentValues v=new ContentValues();v.put("kind",kind);v.put("title",value(title));v.put("requester_name",value(name));v.put("requester_province",value(requesterProvince));v.put("requester_city",value(requesterCity));v.put("specialties",value(specialties));v.put("province",value(province));v.put("city",value(city));v.put("description",value(description));v.put("conditions",value(conditions));v.put("availability",value(availability));v.put("due_date",value(due));v.put("proposed_amount",a.nonNegativeMoney(value(amount)));v.put("work_type",work.getSelectedItem().toString());data.collaboration(v);},this::cooperation);}

    void addPerson(Runnable after){new AlertDialog.Builder(a).setTitle("نوع شخص").setItems(new String[]{"شخص حقیقی","شخص حقوقی","وکیل همکار"},(d,n)->{if(n==2)colleague(null,after);else person(null,after,n);}).show();}
    void colleagues(){a.clear("وکلای همکار","فهرست مشترک پرونده‌ها و قراردادها");a.detailBack=this::people;a.page.addView(button("+ ثبت وکیل همکار",()->colleague(null,this::colleagues)));for(OfficeDb.CollaboratorRecord c:a.db.collaborators())a.page.addView(a.info(c.toString(),c.license+" | "+c.body+" | "+c.phone));}
    void colleague(OfficeDb.CaseRecord caseRecord,Runnable after){
        LinearLayout f=a.form();EditText first=field(f,"نام *",""),last=field(f,"نام خانوادگی *",""),license=field(f,"شماره پروانه",""),phone=field(f,"همراه",""),rank=field(f,"پایه / رتبه",""),province=field(f,"استان",""),city=field(f,"شهر",""),address=field(f,"نشانی",""),notes=field(f,"توضیحات",""),share=field(f,"درصد سهم توافقی","");a.bindLocation(province,city);Spinner body=a.spinner(new String[]{"کانون وکلای دادگستری","مرکز وکلا، کارشناسان رسمی و مشاوران خانواده قوه قضاییه"}),mode=a.spinner(OfficeV101.MODES);f.addView(body);if(caseRecord!=null)f.addView(mode);else share.setVisibility(View.GONE);
        dialog("ثبت وکیل همکار",f,()->{OfficeV101.required(value(first),"نام");OfficeV101.required(value(last),"نام خانوادگی");OfficeV101.location(value(province),value(city));String mobile=InputValidators.normalizeIranianMobile(value(phone));if(!mobile.isEmpty()&&!InputValidators.isValidIranianMobile(mobile))throw new IllegalArgumentException("شماره همراه معتبر نیست");double percent=value(share).isEmpty()?0:Double.parseDouble(InputValidators.normalizeDigits(value(share)));data.db().beginTransaction();try{long id=a.db.addCollaborator(value(first),value(last),value(license),body.getSelectedItem().toString(),mobile,value(notes));data.colleagueDetails(id,value(province),value(city),value(address),value(rank));if(caseRecord!=null)a.db.linkCollaborator(caseRecord.id,id,mode.getSelectedItem().toString(),percent,value(notes));data.db().setTransactionSuccessful();}finally{data.db().endTransaction();}},after);
    }
    void personDetails(long id){ContentValues p=data.person(id);a.clear(OfficeV101.text(p,"name"),"مشخصات و گردش مالی شخص");a.detailBack=this::people;a.page.addView(button("ویرایش مشخصات",()->person(id,()->personDetails(id))));a.page.addView(a.info("اطلاعات تماس",OfficeV101.text(p,"phone")+" | "+OfficeV101.text(p,"telephone")+"\n"+OfficeV101.text(p,"province")+"، "+OfficeV101.text(p,"city")+"\n"+OfficeV101.text(p,"address")));
        long receipts=0,payments=0;for(ContentValues row:data.transactions(null,id,null,null,null,null)){long amount=row.getAsLong("amount");boolean income="payment".equals(OfficeV101.text(row,"kind"));if(income)receipts=Math.addExact(receipts,amount);else payments=Math.addExact(payments,amount);a.page.addView(a.info((income?"دریافتی":"پرداختی")+" · "+a.money(amount),OfficeV101.text(row,"entry_date")+" | "+OfficeV101.text(row,"category")));}a.page.addView(a.info("خالص گردش ثبت‌شده",a.money(receipts-payments)+"\nاین مبلغ مانده تعهد قراردادی نیست."));
    }
    void legal(){a.clear("قوانین و مقررات و آرای وحدت رویه","پایگاه حقوقی");if(a.db.countLegalDocuments()==0)a.page.addView(a.empty("در حال آماده‌سازی اتصال به پایگاه حقوقی"));LinearLayout f=a.form();EditText query=field(f,"عنوان، شماره، ماده یا متن",""),category=field(f,"دسته / موضوع","");Spinner kind=a.spinner(new String[]{"همه","قانون","ماده","رأی وحدت رویه","نظریه مشورتی","مقررات"});f.addView(kind);a.page.addView(f);a.page.addView(button("جست‌وجو",()->{List<ContentValues> rows=data.rows("SELECT * FROM legal_documents WHERE deleted_at IS NULL AND (title LIKE ? OR number LIKE ? OR body LIKE ?) AND (?='' OR subject LIKE ?) ORDER BY title","%"+value(query)+"%","%"+value(query)+"%","%"+value(query)+"%",value(category),"%"+value(category)+"%");ArrayList<ContentValues> results=new ArrayList<>();for(ContentValues row:rows)if(kind.getSelectedItemPosition()==0||kind.getSelectedItem().toString().equals(OfficeV101.text(row,"kind")))results.add(row);if(results.isEmpty()){a.toast("محتوایی مطابق جست‌وجو روی دستگاه موجود نیست");return;}String[] labels=new String[results.size()];for(int i=0;i<labels.length;i++)labels[i]=OfficeV101.text(results.get(i),"title");new AlertDialog.Builder(a).setTitle("نتایج جست‌وجو").setItems(labels,(d,n)->{ContentValues v=results.get(n);a.preview(OfficeV101.text(v,"title"),OfficeV101.text(v,"body")+"\n\nمنبع: "+OfficeV101.text(v,"source_url"));}).show();}));}
}
