plugins { id "com.android.application" }

android {
    namespace "ir.kamranvahdati.lawoffice"
    compileSdk 35
    defaultConfig {
        applicationId "ir.kamranvahdati.lawoffice"
        minSdk 24
        targetSdk 35
        versionCode 8
        versionName "0.8.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
