plugins { id "com.android.application" }

dependencies {
    implementation 'net.zetetic:sqlcipher-android:4.14.1@aar'
    implementation 'androidx.sqlite:sqlite:2.7.0'
}

android {
    namespace "ir.kamranvahdati.lawoffice"
    compileSdk 35
    defaultConfig {
        applicationId "ir.kamranvahdati.lawoffice"
        minSdk 24
        targetSdk 35
        versionCode 9
        versionName "0.8.1"
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
