plugins { id "com.android.application" }

dependencies {
    implementation 'net.zetetic:sqlcipher-android:4.14.1@aar'
    implementation 'androidx.sqlite:sqlite:2.7.0'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}

android {
    buildFeatures { buildConfig true }
    namespace "ir.kamranvahdati.lawoffice"
    compileSdk 35
    defaultConfig {
        applicationId "ir.kamranvahdati.lawoffice"
        minSdk 24
        targetSdk 35
        versionCode 12
        versionName "10.0"
        manifestPlaceholders = [appLabel: "@string/app_name"]
        testInstrumentationRunner "ir.kamranvahdati.lawoffice.OfficeTestRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        preview {
            initWith release
            applicationIdSuffix ".preview"
            versionNameSuffix "-preview"
            matchingFallbacks = ["release"]
            manifestPlaceholders = [appLabel: "وکانو — پیش‌نمایش"]
        }
    }
}
